# Recipe Website — Claude Build Prompt

Build me a personal recipe website to be hosted on GitHub Pages (fully static, no backend). Here are the requirements:

---

## Recipe Storage

- Each recipe lives as its own JSON file inside a `/recipes` folder
- A build script (Node.js) scans the `/recipes` folder and combines all individual recipe JSON files into a single `recipes.json` index file used by the site
- Each recipe JSON file should follow this structure:

```json
{
  "id": "spaghetti-bolognese",
  "name": "Spaghetti Bolognese",
  "description": "A classic Italian meat sauce",
  "servings": 4,
  "tags": ["pasta", "italian", "weeknight"],
  "liked_by": ["kids", "dad", "mum"],
  "ingredients": [
    { "item": "spaghetti", "amount": 400, "unit": "g", "category": "pasta & rice" },
    { "item": "beef mince", "amount": 500, "unit": "g", "category": "meat" }
  ],
  "steps": [
    "Boil salted water and cook spaghetti according to packet instructions.",
    "Brown the mince in a pan over high heat."
  ],
  "notes": "Freezes well. Make double and freeze half."
}
```

---

## Site Structure

- `index.html` — homepage with search, filters, and recipe grid
- `recipe.html` — single recipe view (loads recipe by URL parameter, e.g. `recipe.html?id=spaghetti-bolognese`)
- `planner.html` — weekly meal planner and shopping list
- `recipes.json` — the combined index built by the build script
- `/recipes/` — folder of individual recipe JSON files
- `build.js` — the Node.js build script
- `style.css` — shared stylesheet
- `app.js` — shared JavaScript

---

## Search & Filter (index.html)

- Search box that searches recipe name, ingredients, and tags simultaneously using fuzzy matching (use Fuse.js via CDN)
- Filter buttons for `liked_by` family members (dynamically generated from the data)
- Filter buttons for tags/categories (dynamically generated from the data)
- Multiple filters can be active at the same time
- Recipe results shown as cards with name, description, tags, and liked_by indicators
- Clicking a card goes to `recipe.html?id=...`

---

## Recipe Page (recipe.html)

- Loads and displays the full recipe from `recipes.json` using the `id` URL parameter
- Shows: name, description, servings, ingredients, steps, notes, tags, liked_by
- Has an "Add to weekly planner" button that saves the recipe ID to localStorage

---

## Weekly Planner & Shopping List (planner.html)

- Shows all recipes currently saved to the weekly planner (read from localStorage)
- Each planned recipe can be removed
- A shopping list is automatically generated by combining all ingredients across planned recipes
- Ingredients with the same item name and unit are combined (e.g. two recipes needing garlic cloves are summed)
- Shopping list is grouped by ingredient category
- A print button triggers a clean print view of the shopping list
- A "Clear planner" button resets everything

---

## Technical Requirements

- Vanilla HTML, CSS, and JavaScript only (no frameworks)
- Fuse.js loaded via CDN for fuzzy search
- All data loading uses `fetch()` against `recipes.json`
- `localStorage` used for persisting the weekly planner selections
- Must work correctly when served by GitHub Pages
- The build script (`build.js`) should be run with `node build.js` and outputs `recipes.json` to the root
- Include a `package.json` with a `"build": "node build.js"` script
- Include 5 varied example recipes to demonstrate the structure

---

## Style

- Clean, minimal, functional design — this is a personal site, not a showcase
- Mobile friendly
- Print stylesheet for the shopping list